import groovy.json.JsonOutput

plugins {
    id 'com.gradleup.shadow'
}

def isFabric = "${project.name}".toString().equals("fabric")
def isForge = "${project.name}".toString().equals("forge")
def isNeoForge = "${project.name}".toString().equals("neoforge")

configurations {
    shadowImplementation
    implementation.extendsFrom shadowImplementation
}

dependencies {
    shadowImplementation 'com.moandjiezana.toml:toml4j:0.7.2'
}

if (isFabric || isForge || isNeoForge) {
    shadowJar {
        configurations = [project.configurations.shadowImplementation]

        relocate('com.moandjiezana', 'me.ichun.shadow.com.moandjiezana')

        dependencies {
            exclude(dependency('com.google.code.gson:gson:'))
        }

        if (isForge || isNeoForge) {
            archiveClassifier.set("")
        }
    }

    components.java.withVariantsFromConfiguration(configurations.shadowRuntimeElements) {
        skip()
    }

    if (isFabric) {
        tasks.named("remapJar").configure {
            dependsOn "shadowJar"
            inputFile = shadowJar.archiveFile.get().asFile
        }
    }
    else {
        jar {
            finalizedBy "shadowJar"
        }
        tasks.named("generateMetadataFileForMavenJavaPublication").configure {
            mustRunAfter "shadowJar"
        }
    }
}

if("${project.name}".toString().equals("common")) {
    tasks.register("createHeadsZip", Zip) {
        archiveFileName = "heads.zip"
        destinationDirectory = layout.buildDirectory.dir('assets')
        from fileTree(dir: "${project.rootDir}/heads")
    }

    tasks.register("createThemesZip", Zip) {
        archiveFileName = "themes.zip"
        destinationDirectory = layout.buildDirectory.dir('assets')
        from fileTree(dir: "${project.rootDir}/themes")
    }

    tasks.named("compileJava").configure {
        dependsOn createHeadsZip, createThemesZip
    }
}
else if(!"${project.name}".toString().equals("api")) {
    if("${project.name}".toString().equals("fabric")) {
        tasks.register('generateFabricLoaderDependenciesOverrideConfig') {
            group = "Fabric"
            doLast {
                def runDir = gradle.root != null ? "${gradle.root.getRootProject().rootDir}/fabric/run" : "${project.projectDir}/run"
                def configDir = file("${runDir}/config/")
                if(!configDir.exists()) { configDir.mkdirs() }
                def configFile = file("${configDir}/fabric_loader_dependencies.json")
                println "Creating config file at: ${configFile}"
                def modIdToDep = [:]
                def json = ["version": 1, "overrides": modIdToDep]
                def modsToOverride = ["betterthanbunnies","betterthanllamas","contentcreatorintegration","deathcounter","ding","dogslie","hotbarswapper","limitedlives","partyparrots","serverpause"]
                modsToOverride.each { id ->
                    def ignoreMap = ["ichunutil": "IGNORED"]
                    def depToDef = ["-depends": ignoreMap]
                    modIdToDep.put(id, depToDef)
                }
                file(configFile).text = JsonOutput.prettyPrint(JsonOutput.toJson(json))
            }
        }
    }

    tasks.named('processResources', ProcessResources).configure {
        inputs.files project(":common").createThemesZip
        from(project(":common").layout.buildDirectory.dir('assets').get()) {
            include "themes.zip"
        }
    }
}
